
PLANE:
  RANSAC_N: 3
  RANSAC_THRESHOLD: 0.01
  RANSAC_ITERATIONS: 1000
  Y_FLOOR: 0.0
  Z_FLOOR: 0.1
  Z_CEIL: 0.2
  CENTER_OFFSET: 0.15

IMAGE:
  HEIGHT: 480
  WIDTH: 640
  FILE_PATH: '/home/jan/Desktop/pandavision/calibration/captures'

SEGMENT:
  SAVE_MASK: True

SIMULINK:
  ENGINE_NAME: MATLAB_2731
  SIMULINK_SESSION_NAME: Controller_taskSpace_GraspObject
  ACTIVATE_ATTRIBUTE: CONTROL
  COORDINATE_ATTRIBUTE: TARGET
  ANGLE_ATTRIBUTE: ANGLE
  COORDINATE_HOME_ATTRIBUTE: TARGET_HOME
  ANGLE_HOME_ATTRIBUTE: ANGLE_HOME

REALSENSE:
    SERIAL: 840412060493
    COLOR_FORMAT: RS2_FORMAT_BGR8,
    COLOR_RESOLUTION: 640,480
    DEPTH_FORMAT: RS2_FORMAT_Z16
    DEPTH_RESOLUTION: 640,480
    VISUAL_PRESET: RS2_RS400_VISUAL_PRESET_HIGH_ACCURACY
